a <- 0.05
d <- read.csv("../data/gashimova/surgery.csv", check.names = F)
d$group <- as.factor(d$group)
d_psh <- subset(d, d$group != 6)

sink("surgery/сравнение показателей.txt")
for(i in 3:11){
  title <- names(d)[i]
  medians <- tapply(d[,i], d[,1], function(x) median(x, na.rm = T))
  quantile.25 <- tapply(d[,i], d[,1], function(x) quantile(x, 0.25, na.rm = T))
  quantile.75 <- tapply(d[,i], d[,1], function(x) quantile(x, 0.75, na.rm = T))
  kruskal <- kruskal.test(d[,i], d[,1])
  pairwise <- pairwise.wilcox.test(d[,i], d[,1], p.adjust.method = 'holm')
  cat(paste("Показатель", title, sep = ' - '))
  cat("\r\n")
  for(j in 1:length(levels(d$group))){
    cat(paste("Медиана и 25%-75% квартили в группе ", levels(d$group)[j], paste(" = ", medians[j], " (", quantile.25[j], " - ", quantile.75[j], ") ", sep = ""), sep = ""))
    cat("\r\n")
  }
  cat(paste("Метод", kruskal$method, sep = ' - '))
  cat("\r\n")
  cat(paste("Значение p", round(kruskal$p.value, 6), sep = ' = '))
  cat("\r\n")
  cat(paste("Метод", pairwise$method, sep = ' - '))
  cat("\r\n")
  cat(paste("Группы 0-1. Значение p", round(pairwise$p.value[1, 1], 6), sep = ' = '))
  cat("\r\n")
  cat(paste("Группы 0-3. Значение p", round(pairwise$p.value[2, 1], 6), sep = ' = '))
  cat("\r\n")
  cat(paste("Группы 0-6. Значение p", round(pairwise$p.value[3, 1], 6), sep = ' = '))
  cat("\r\n")
  cat(paste("Группы 1-3. Значение p", round(pairwise$p.value[2, 2], 6), sep = ' = '))
  cat("\r\n")
  cat(paste("Группы 1-6. Значение p", round(pairwise$p.value[3, 2], 6), sep = ' = '))
  cat("\r\n")
  cat(paste("Группы 3-6. Значение p", round(pairwise$p.value[3, 3], 6), sep = ' = '))
  cat("\r\n")
  cat("\r\n")
}
title <- names(d_psh)[12]
medians <- tapply(d_psh[,12], d_psh[,1], function(x) median(x, na.rm = T))
quantile.25 <- tapply(d_psh[,12], d_psh[,1], function(x) quantile(x, 0.25, na.rm = T))
quantile.75 <- tapply(d_psh[,12], d_psh[,1], function(x) quantile(x, 0.75, na.rm = T))
kruskal <- kruskal.test(d_psh[,12], d_psh[,1])
pairwise <- pairwise.wilcox.test(d_psh[,12], d_psh[,1], p.adjust.method = 'holm')
cat(paste("Показатель", title, sep = ' - '))
cat("\r\n")
for(j in 1:length(levels(d_psh$group))){
  cat(paste("Медиана и 25%-75% квартили в группе ", levels(d_psh$group)[j], paste(" = ", medians[j], " (", quantile.25[j], " - ", quantile.75[j], ") ", sep = ""), sep = ""))
  cat("\r\n")
}
cat(paste("Метод", kruskal$method, sep = ' - '))
cat("\r\n")
cat(paste("Значение p", round(kruskal$p.value, 6), sep = ' = '))
cat("\r\n")
cat(paste("Метод", pairwise$method, sep = ' - '))
cat("\r\n")
cat(paste("Группы 0-1. Значение p", round(pairwise$p.value[1, 1], 6), sep = ' = '))
cat("\r\n")
cat(paste("Группы 0-3. Значение p", round(pairwise$p.value[2, 1], 6), sep = ' = '))
cat("\r\n")
cat(paste("Группы 1-3. Значение p", round(pairwise$p.value[2, 2], 6), sep = ' = '))
cat("\r\n")
cat("\r\n")
sink()