library('tidyverse')
df <- read.csv('~/R/data/unknown/ba.csv')
df$sex <- factor(df$sex)
df$age <- factor(df$age)
df$obesity <- factor(df$obesity)
df$duration <- factor(df$duration)
df$severity <- factor(df$severity)
dependent_variables <- c('asthma', 'treatment', 'anxiety', 'communication')
sink('~/R/stud_stat/unknown/output/output.txt')
for(i in 1:length(names(df))){
  if(names(df)[i] %in% dependent_variables){
    d_var <- names(df)[i]
    cat(d_var)
    cat('\n')
    cat("пол")
    cat("\n")
    cat("среднее значение и ошибка")
    cat('\n')
    cat(levels(df$sex))
    cat("\n")
    cat(paste(tapply(df[,i], df$sex, function(x) round(mean(x, rm.na = T), 4)), tapply(df[,i], df$sex, function(x) round(sd(x)/sqrt(length(x)), 4)), sep = '±'))
    cat("\n")
    cat("критерий Манна-Уитни")
    cat("\n")
    cat(wilcox.test(df[,i] ~ df$sex, df)$p.value)
    cat("\n")
    
    cat('\n')
    cat("возраст")
    cat("\n")
    cat("среднее значение и ошибка")
    cat("\n")
    cat(levels(df$age))
    cat("\n")
    cat(paste(tapply(df[,i], df$age, function(x) round(mean(x, rm.na = T), 4)), tapply(df[,i], df$age, function(x) round(sd(x)/sqrt(length(x)), 4)), sep = '±'))
    cat("\n")
    cat("критерий Краскала-Уоллиса")
    cat("\n")
    cat(kruskal.test(df[,i] ~ df$age, df)$p.value)
    cat("\n")
    
    cat("\n")
    cat("продолжительность")
    cat("\n")
    cat("среднее значение и ошибка")
    cat("\n")
    cat(levels(df$duration))
    cat("\n")
    cat(paste(tapply(df[,i], df$duration, function(x) round(mean(x, rm.na = T), 4)), tapply(df[,i], df$duration, function(x) round(sd(x)/sqrt(length(x)), 4)), sep = '±'))
    cat("\n")
    cat("критерий Манна-Уитни")
    cat("\n")
    cat(wilcox.test(df[,i] ~ df$duration, df)$p.value)
    cat("\n")
    
    cat('\n')
    cat("тяжесть")
    cat("\n")
    cat("среднее значение и ошибка")
    cat("\n")
    cat(levels(df$severity))
    cat("\n")
    cat(paste(tapply(df[,i], df$severity, function(x) round(mean(x, rm.na = T), 4)), tapply(df[,i], df$severity, function(x) round(sd(x)/sqrt(length(x)), 4)), sep = '±'))
    cat("\n")
    cat("критерий Краскала-Уоллиса")
    cat("\n")
    cat(kruskal.test(df[,i] ~ df$severity, df)$p.value)
    cat("\n")
    
    cat("\n")
    cat("ожирение")
    cat("\n")
    cat("среднее значение и ошибка")
    cat("\n")
    cat(levels(df$obesity))
    cat("\n")
    cat(paste(tapply(df[,i], df$obesity, function(x) round(mean(x, rm.na = T), 4)), tapply(df[,i], df$obesity, function(x) round(sd(x)/sqrt(length(x)), 4)), sep = '±'))
    cat("\n")
    cat("критерий Манна-Уитни")
    cat("\n")
    cat(wilcox.test(df[,i] ~ df$obesity, df)$p.value)
    cat("\n")
    cat("\n")
    }
}
sink()
