library(epitools)
self <- read.csv('self.csv') 
self$Дата <- strftime(self$Дата)
self$week.year <- paste(strftime(self$Дата, "%Y"), as.week(self$Дата, sunday = F)$week, sep=(" "))
self$month.year <- paste(strftime(self$Дата, "%Y"), sprintf("%02d", as.month(self$Дата)$mon), sep=(" "))
self$week.year <- factor(self$week.year)
self$month.year <- factor(self$month.year)
means.weight.week <- by(self$Вес, self$week.year, mean)
png(filename = 'Вес по неделям.png', width = length(levels(self$week.year))*75)
boxplot(self$Вес..кг ~ self$week.year, xlab = "Недели", ylab = "Вес, кг")
points(1:length(means.weight.week), means.weight.week, pch = 23, cex = 0.75, bg = "red")
lines(by(self$Вес..кг, self$week.year, mean))
text(1:length(means.weight.week + 2), means.weight.week, labels = format(means.weight.week, digit = 4), pos = 3)
dev.off()
means.pulse <- by(self$ЧСС, self$week.year, mean)
png(filename = 'ЧСС.png')
boxplot(self$ЧСС ~ self$week.year, xlab = "Недели", ylab = "ЧСС")
points(1:length(means.pulse), means.pulse, pch = 23, cex = 0.75, bg = "red")
lines(by(self$ЧСС, self$week.year, mean))
text(1:length(means.pulse + 2), means.pulse, labels = format(means.pulse, digit = 4), pos = 3)
dev.off()
means.weight.month <- by(self$Вес, self$month.year, mean)
png(filename = 'Вес по месяцам.png', width = length(levels(self$month.year))*100)
boxplot(self$Вес..кг ~ self$month.year, xlab = "Месяцы", ylab = "Вес, кг")
points(1:length(means.weight.month), means.weight.month, pch = 23, cex = 0.75, bg = "red")
lines(by(self$Вес..кг, self$month.year, mean))
text(1:length(means.weight.month + 2), means.weight.month, labels = format(means.weight.month, digit = 4), pos = 3)
dev.off()